version: '3'
services:
  proxycat:
    image: ghcr.io/nssanc/proxycat:latest
    # build: .  # 本地构建使用此选项
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "1080:1080"
      - "5000:5000"
    volumes:
      - ./config:/app/config
    restart: unless-stopped
    network_mode: "bridge"