services:
  proxycat:
    image: ghcr.io/nssanc/proxycat:latest
    # build: .  # 本地构建使用此选项
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "1080:1080"
      - "5000:5000"
    volumes:
      - ./config/config.ini:/app/config/config.ini
      - ./config/ip.txt:/app/config/ip.txt
      - ./config/blacklist.txt:/app/config/blacklist.txt
      - ./config/whitelist.txt:/app/config/whitelist.txt
    restart: unless-stopped
    network_mode: "bridge"