services:
  proxycat:
    image: ghcr.io/nssanc/proxycat:latest
    container_name: proxycat
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "1080:1080"
      - "5000:5000"
    volumes:
      - ./config:/app/config
    restart: unless-stopped
